#!/usr/bin/env sh

if ! [ $# -ge 1 ]; then
	echo "Usage: patch_hardlinks [directory] [from] [to]"
	exit 1
fi

cd $1
shift 1

for i in $(grep -R -l "$1"); do
	echo "Patching $i"
	sed -i "s%$1%$2%g" $i;
done
